# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'invoice.ui',
# licensing of 'invoice.ui' applies.
#
# Created: Tue Feb 19 09:51:24 2019
#      by: pyside2-uic  running on PySide2 5.12.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Invoice(object):
    def setupUi(self, Invoice):
        Invoice.setObjectName("Invoice")
        Invoice.resize(641, 450)
        self.cboDocType = QtWidgets.QComboBox(Invoice)
        self.cboDocType.setGeometry(QtCore.QRect(83, 20, 111, 22))
        self.cboDocType.setCurrentText("")
        self.cboDocType.setObjectName("cboDocType")
        self.label = QtWidgets.QLabel(Invoice)
        self.label.setGeometry(QtCore.QRect(20, 24, 58, 13))
        self.label.setObjectName("label")
        self.txtDocNumber = QtWidgets.QLineEdit(Invoice)
        self.txtDocNumber.setGeometry(QtCore.QRect(260, 20, 91, 20))
        self.txtDocNumber.setCursorPosition(1)
        self.txtDocNumber.setObjectName("txtDocNumber")
        self.txtDocDate = QtWidgets.QLineEdit(Invoice)
        self.txtDocDate.setGeometry(QtCore.QRect(410, 20, 71, 20))
        self.txtDocDate.setObjectName("txtDocDate")
        self.label_2 = QtWidgets.QLabel(Invoice)
        self.label_2.setGeometry(QtCore.QRect(370, 24, 33, 13))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Invoice)
        self.label_4.setGeometry(QtCore.QRect(210, 24, 41, 13))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Invoice)
        self.label_3.setGeometry(QtCore.QRect(500, 24, 42, 13))
        self.label_3.setObjectName("label_3")
        self.cboCurrency = QtWidgets.QComboBox(Invoice)
        self.cboCurrency.setGeometry(QtCore.QRect(550, 20, 71, 22))
        self.cboCurrency.setObjectName("cboCurrency")
        self.label_5 = QtWidgets.QLabel(Invoice)
        self.label_5.setGeometry(QtCore.QRect(20, 54, 53, 13))
        self.label_5.setObjectName("label_5")
        self.txtDocCustomer = QtWidgets.QLineEdit(Invoice)
        self.txtDocCustomer.setGeometry(QtCore.QRect(83, 50, 81, 20))
        self.txtDocCustomer.setObjectName("txtDocCustomer")
        self.label_6 = QtWidgets.QLabel(Invoice)
        self.label_6.setGeometry(QtCore.QRect(190, 54, 60, 13))
        self.label_6.setObjectName("label_6")
        self.btnItem = QtWidgets.QPushButton(Invoice)
        self.btnItem.setGeometry(QtCore.QRect(550, 50, 71, 23))
        self.btnItem.setObjectName("btnItem")
        self.treeProducts = QtWidgets.QTreeWidget(Invoice)
        self.treeProducts.setGeometry(QtCore.QRect(20, 90, 601, 281))
        self.treeProducts.setObjectName("treeProducts")
        self.btnSave = QtWidgets.QPushButton(Invoice)
        self.btnSave.setGeometry(QtCore.QRect(100, 410, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(Invoice)
        self.btnCancel.setGeometry(QtCore.QRect(250, 410, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.lblTotalLetters = QtWidgets.QLabel(Invoice)
        self.lblTotalLetters.setGeometry(QtCore.QRect(20, 380, 101, 13))
        self.lblTotalLetters.setObjectName("lblTotalLetters")
        self.label_8 = QtWidgets.QLabel(Invoice)
        self.label_8.setGeometry(QtCore.QRect(410, 390, 43, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Invoice)
        self.label_9.setGeometry(QtCore.QRect(490, 390, 43, 13))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Invoice)
        self.label_10.setGeometry(QtCore.QRect(590, 390, 24, 13))
        self.label_10.setObjectName("label_10")
        self.lblSubTotal = QtWidgets.QLabel(Invoice)
        self.lblSubTotal.setGeometry(QtCore.QRect(390, 410, 60, 13))
        self.lblSubTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSubTotal.setObjectName("lblSubTotal")
        self.lblTotal = QtWidgets.QLabel(Invoice)
        self.lblTotal.setGeometry(QtCore.QRect(550, 410, 65, 13))
        self.lblTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTotal.setObjectName("lblTotal")
        self.lblTax = QtWidgets.QLabel(Invoice)
        self.lblTax.setGeometry(QtCore.QRect(470, 410, 65, 13))
        self.lblTax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTax.setObjectName("lblTax")

        self.retranslateUi(Invoice)
        self.cboDocType.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Invoice)

    def retranslateUi(self, Invoice):
        Invoice.setWindowTitle(QtWidgets.QApplication.translate("Invoice", "Venta", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Invoice", "Documento:", None, -1))
        self.txtDocNumber.setText(QtWidgets.QApplication.translate("Invoice", "F001-00015215", None, -1))
        self.txtDocDate.setPlaceholderText(QtWidgets.QApplication.translate("Invoice", "dd/mm/yyyy", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Invoice", "Fecha:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Invoice", "Número:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Invoice", "Moneda:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Invoice", "RUC / DNI:", None, -1))
        self.txtDocCustomer.setText(QtWidgets.QApplication.translate("Invoice", "10444948430", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Invoice", "Razón Social", None, -1))
        self.btnItem.setText(QtWidgets.QApplication.translate("Invoice", "Item", None, -1))
        self.treeProducts.headerItem().setText(0, QtWidgets.QApplication.translate("Invoice", "Código", None, -1))
        self.treeProducts.headerItem().setText(1, QtWidgets.QApplication.translate("Invoice", "Cantidad", None, -1))
        self.treeProducts.headerItem().setText(2, QtWidgets.QApplication.translate("Invoice", "Unid. Medida", None, -1))
        self.treeProducts.headerItem().setText(3, QtWidgets.QApplication.translate("Invoice", "Descripción", None, -1))
        self.treeProducts.headerItem().setText(4, QtWidgets.QApplication.translate("Invoice", "Precio Unitario", None, -1))
        self.treeProducts.headerItem().setText(5, QtWidgets.QApplication.translate("Invoice", "Total", None, -1))
        self.btnSave.setText(QtWidgets.QApplication.translate("Invoice", "Guardar", None, -1))
        self.btnCancel.setText(QtWidgets.QApplication.translate("Invoice", "Cancelar", None, -1))
        self.lblTotalLetters.setText(QtWidgets.QApplication.translate("Invoice", "IMPORTE EN LETRAS", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("Invoice", "Sub total", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("Invoice", "IGV 18%", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("Invoice", "Total", None, -1))
        self.lblSubTotal.setText(QtWidgets.QApplication.translate("Invoice", "100,000.00", None, -1))
        self.lblTotal.setText(QtWidgets.QApplication.translate("Invoice", "118,000.00", None, -1))
        self.lblTax.setText(QtWidgets.QApplication.translate("Invoice", "18,000.00", None, -1))

